secretsprovider: awskms://alias/pulumi-poc-key?region=ap-southeast-1
encryptedkey: AQICAHiRyrDYpmoNFuuoBhq8p9/PrgLTjbtfnOud21njngySsgF3DcyYDmS2kRdDibI/p7TKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMAh/6mTosaqOysGJnAgEQgDsKNi1K5kjzTjER98wf5LD3n40qe5Yc5RyjIFfz7+/lGZ8K50c7Y/YoMSn4H5XyxBS7ClgWIXvkt//bjA==
config:
  aws:region: ap-southeast-1
  infra-poc:vpcCidr: 10.20.0.0/16
  infra-poc:desiredCount: "1"
  infra-poc:dbInstanceClass: db.t4g.micro
  infra-poc:protectStateful: "false"
  infra-poc:deletionProtection: "false"
  infra-poc:enableTgw: "false"
