config:
  aws:region: ap-southeast-1
  infra-poc:vpcCidr: 10.10.0.0/16
  infra-poc:desiredCount: "1"
  infra-poc:dbInstanceClass: db.t4g.micro
  infra-poc:protectStateful: "false"
  infra-poc:deletionProtection: "false"
  infra-poc:ecrRepositoryName: poc-app
  infra-poc:expectedAccount:
    secure: v1:4F/FOWalgH4wqZBI:W5OiLlzhg8dqML7SAaUpX5B4Pk68nDT0tpNT8w==
secretsprovider: awskms://alias/pulumi-poc-key?region=ap-southeast-1
encryptedkey: AQICAHi+3Okk2yf/lESn8DwqfJBDJdSKTARmnF3agQMQKpXZCAGax5ztC56PDEuYJ+mLQZYoAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM48FzNSk4epZ9018sAgEQgDvuDHtBwrcA9A/AB6LOTkXIXIIwGWSyGGnJGIYL+5bG7f0G1VSvW3fForH7vXM+h/NwqkhDYX43n9mXoQ==
