config:
  aws:region: ap-southeast-1
  infra-poc:vpcCidr: 10.30.0.0/16
  infra-poc:desiredCount: "2"
  infra-poc:dbInstanceClass: db.t4g.small
  infra-poc:protectStateful: "false"
  infra-poc:deletionProtection: "false"
  infra-poc:ecrRepositoryName: poc-app
  infra-poc:expectedAccount:
    secure: v1:1QYuQkgY6pQBa/3z:m5mo7yWYJYCBPYgIJbdru4kX40r+acIGEL4U4g==
secretsprovider: awskms://alias/pulumi-poc-key?region=ap-southeast-1
encryptedkey: AQICAHi+3Okk2yf/lESn8DwqfJBDJdSKTARmnF3agQMQKpXZCAGaeBLWCTpmsuYX/DrW2PRnAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMaH/ifUG9C0PJS5woAgEQgDucQ/V0TI4FjQ95ZknxZgS8ZD7GCXfKjo0xKlpgzpX2F48JtSg0diNYpJU3wu+gOAG/YKsysr9ezCHifQ==
