name: "TMP AccessDenied test"
on:
  pull_request:
    branches: [dev]
permissions:
  id-token: write
  contents: read
jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: infra/go.mod
          cache-dependency-path: infra/go.sum
      - uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_DEV_PREVIEW }}
          aws-region: ap-southeast-1
      - uses: pulumi/actions@cd99a7f8865434dd3532b586a26f9ebea596894f # v5.5.1
      - working-directory: ./infra/workload
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          pulumi login "s3://pulumi-state-poc-${ACCOUNT_ID}?region=ap-southeast-1"
          pulumi stack select dev
          pulumi config set imageTag cc6d42a
          echo "role: $(aws sts get-caller-identity --query Arn --output text | sed -E 's/[0-9]{12}/<account>/g')"
          set +e
          pulumi up --yes 2>&1 | sed -E 's/[0-9]{12}/<account>/g'
          echo "pulumi up exit code: ${PIPESTATUS[0]}"
